### ISSUE TITLE
Failures in the test suite running on latest Bazel

### ISSUE THREAD

**Issue by stefanbucur** [bazelbuild/rules_fuzzing#206]
See for example https://github.com/bazelbuild/rules_fuzzing/actions/runs/2522403386:

```
ERROR: Traceback (most recent call last):
	File "/home/runner/work/rules_fuzzing/rules_fuzzing/WORKSPACE", line 35, column 12, in <toplevel>
		jazzer_init()
	File "/home/runner/.cache/bazel/_bazel_runner/fe6cb6e248ce6cff4727b846eff77c1f/external/jazzer/init.bzl", line 26, column 24, in jazzer_init
		kotlin_repositories()
	File "/home/runner/.cache/bazel/_bazel_runner/fe6cb6e248ce6cff4727b846eff77c1f/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl", line 96, column 21, in kotlin_repositories
		rules_repository(
Error in repository_rule: invalid repository name '': must start with a letter and contain only letters, digits, '.', '-', or '_'
ERROR: error loading package '': Encountered error while reading extension file 'setup.bzl': no such package '@io_bazel_stardoc//': error loading package 'external': Could not load //external package
```

Seems to be related to a Jazzer dependency on Kotlin. CC @fmeum for visibility.

**Comment by fmeum** [comment]
Caused by https://github.com/bazelbuild/bazel/issues/15667, will need to wait for that to be resolved in a rules_kotlin release.

**Comment by stefanbucur** [comment]
https://github.com/bazelbuild/bazel/issues/15667 seems to be fixed now? FWIW, rules_fuzzing still fails when running on the latest Bazel.

**Comment by fmeum** [comment]
I would have to update the rules_kotlin pin. In the meantime, Jazzer has been heavily refactored and is now available as a prebuilt jar on Maven. I am planning to make use of this new architecture to simplify the way Jazzer is loaded and run by rules_fuzzing.
